### ISSUE TITLE
setup-dev-env.sh reorganization

### ISSUE THREAD

**Issue by Voursstrreds** [bounverif/ansible-collection-ros#1]
Installing step requires this script to be run by user.

Argument taking mechanism should be implemented via Ansible. 
- All the arguments this shell script takes must be implemented.
- A standalone playbook must do this. Also that playbook should run other playbooks in itself.
- Installing steps must be transferred to Ansible playbook exactly.

**Comment by doganulus** [comment]
This issue is specific to a collection (Autoware). 

This is to be discussed for reference implementations.
