### ISSUE TITLE
xml wrapper

### ISSUE THREAD

**Issue by Voursstrreds** [bounverif/ansible-collection-ros#2]
An xml file wrapper is required to get rid of rosdep dependencies. New format should be include all the features that rosdep provides and other new features that Ansible provides.

These features are:
- Package version selection
- More readable yml file replacing for new repositories.

Requirements for this quest is:
- An xml reader implemented as an Ansible role.
- Emposing a new similar standard as yml file.
- Possibly a converter between those.

**Comment by doganulus** [comment]
See https://docs.ansible.com/ansible/latest/collections/community/general/xml_module.html
