### ISSUE TITLE
Automatizing ROS installation

### ISSUE THREAD

**Issue by Voursstrreds** [bounverif/ansible-collection-ros#3]
As defined in [ros documentation](http://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html) installing steps can be automatized via Ansible. In order to provide required flexibility, all the options defined in these existing commands could be set by user by passing flags and arguments.

The design properties are:
- It must be a role.
- An argument parser is required.

**Comment by doganulus** [comment]
See https://github.com/autowarefoundation/autoware/tree/main/ansible/roles/ros2
